pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }

    plugins {
        id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention'
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)

    repositories {
        mavenCentral()
        maven { url = uri("https://jitpack.io") }
        maven { url = uri("https://repo.jenkins-ci.org/public/") } // optional
    }
}

rootProject.name = "ircafe"

include 'ircafe-plugin-api'
include 'ircafe-builtins-notify'
include 'ircafe-builtins-embed'
include 'ircafe-builtins-input'
include 'ircafe-builtins-outbound'
include 'ircafe-builtins-commands'
include 'ircafe-builtins-backend'
include 'ircafe-builtins-ui'
include 'ircafe-builtins-translation'
include 'ircafe-builtins-bouncer'
include 'ircafe-builtins-ircv3-chat-history'
include 'ircafe-builtins-ircv3-multiline'
include 'ircafe-builtins-ircv3-read-marker'
include 'ircafe-builtins-ircv3-message-redaction'
include 'ircafe-builtins-ircv3-sts'
include 'ircafe-builtins-ircv3-sasl'
include 'ircafe-builtins-ircv3-reply'
include 'ircafe-builtins-ircv3-reactions'
include 'ircafe-builtins-ircv3-typing'
include 'ircafe-builtins-ircv3-channel-context'
include 'ircafe-builtins-ircv3-message-edit'
include 'ircafe-builtins-ircv3-message-tags'
include 'ircafe-builtins-ircv3-message-id'
include 'ircafe-builtins-ircv3-server-time'
include 'ircafe-builtins-ircv3-echo-message'
include 'ircafe-builtins-ircv3-standard-replies'
include 'ircafe-builtins-ircv3-account-tag'
include 'ircafe-builtins-ircv3-labeled-response'
include 'ircafe-builtins-ircv3-away-notify'
include 'ircafe-builtins-ircv3-account-notify'
include 'ircafe-builtins-ircv3-extended-join'
include 'ircafe-builtins-ircv3-chghost'
include 'ircafe-builtins-ircv3-setname'
include 'ircafe-builtins-ircv3-invite-notify'
include 'ircafe-builtins-ircv3-monitor'
include 'ircafe-builtins-ircv3-extended-monitor'
include 'ircafe-builtins-ircv3-multi-prefix'
include 'ircafe-builtins-ircv3-userhost-in-names'
include 'ircafe-builtins-ircv3-user-identity'
include 'ircafe-builtins-ircv3-negotiation'
include 'ircafe-builtins-ircv3-cap-notify'
include 'ircafe-builtins-ircv3-batch'
include 'ircafe-builtins-ircv3-znc-playback'
include 'ircafe-feature-commands'
include 'ircafe-feature-translation'
include 'ircafe-feature-embed'
include 'ircafe-feature-bouncer'
include 'ircafe-feature-notify'
include 'ircafe-feature-user-lookup'
include 'ircafe-feature-ircv3-common'
include 'ircafe-feature-ircv3-negotiation'
include 'ircafe-feature-ircv3-message-tags'
include 'ircafe-feature-ircv3-message-id'
include 'ircafe-feature-ircv3-server-time'
include 'ircafe-feature-ircv3-echo-message'
include 'ircafe-feature-ircv3-labeled-response'
include 'ircafe-feature-ircv3-multiline'
include 'ircafe-feature-ircv3-chat-history'
include 'ircafe-feature-ircv3-reply'
include 'ircafe-feature-ircv3-reactions'
include 'ircafe-feature-ircv3-channel-context'
include 'ircafe-feature-ircv3-typing'
include 'ircafe-feature-ircv3-read-marker'
include 'ircafe-feature-ircv3-message-redaction'
include 'ircafe-feature-ircv3-message-edit'
include 'ircafe-feature-ircv3-sasl'
include 'ircafe-feature-ircv3-sts'
include 'ircafe-feature-ircv3-away-notify'
include 'ircafe-feature-ircv3-account-notify'
include 'ircafe-feature-ircv3-extended-join'
include 'ircafe-feature-ircv3-chghost'
include 'ircafe-feature-ircv3-setname'
include 'ircafe-feature-ircv3-invite-notify'
include 'ircafe-feature-ircv3-monitor'
include 'ircafe-feature-ircv3-standard-replies'
include 'ircafe-feature-ircv3-account-tag'
include 'ircafe-feature-ircv3-user-identity'
include 'ircafe-feature-ircv3-batch'
include 'ircafe-feature-ircv3-znc-playback'
