package cafe.woden.ircclient.ui.settings;

import cafe.woden.ircclient.model.NotificationRule;
import java.util.List;

public record UiSettings(
    String theme,
    String chatFontFamily,
    int chatFontSize,
    boolean autoConnectOnStart,
    boolean trayEnabled,
    boolean trayCloseToTray,
    boolean trayMinimizeToTray,
    boolean trayStartMinimized,
    boolean trayNotifyHighlights,
    boolean trayNotifyPrivateMessages,
    boolean trayNotifyConnectionState,
    boolean trayNotifyOnlyWhenUnfocused,
    boolean trayNotifyOnlyWhenMinimizedOrHidden,
    boolean trayNotifySuppressWhenTargetActive,
    boolean trayLinuxDbusActionsEnabled,
    NotificationBackendMode trayNotificationBackendMode,
    boolean imageEmbedsEnabled,
    boolean imageEmbedsCollapsedByDefault,
    int imageEmbedsMaxWidthPx,
    int imageEmbedsMaxHeightPx,
    boolean imageEmbedsAnimateGifs,
    boolean linkPreviewsEnabled,
    boolean linkPreviewsCollapsedByDefault,
    boolean presenceFoldsEnabled,
    boolean ctcpRequestsInActiveTargetEnabled,
    boolean typingIndicatorsEnabled,
    boolean typingIndicatorsReceiveEnabled,
    String typingIndicatorsTreeStyle,
    boolean timestampsEnabled,
    String timestampFormat,
    boolean timestampsIncludeChatMessages,
    boolean timestampsIncludePresenceMessages,
    int chatHistoryInitialLoadLines,
    int chatHistoryPageSize,
    int chatHistoryAutoLoadWheelDebounceMs,
    int chatHistoryLoadOlderChunkSize,
    int chatHistoryLoadOlderChunkDelayMs,
    int chatHistoryLoadOlderChunkEdtBudgetMs,
    boolean chatHistoryDeferRichTextDuringBatch,
    int chatHistoryRemoteRequestTimeoutSeconds,
    int chatHistoryRemoteZncPlaybackTimeoutSeconds,
    int chatHistoryRemoteZncPlaybackWindowMinutes,
    int commandHistoryMaxSize,
    int chatTranscriptMaxLinesPerTarget,
    boolean clientLineColorEnabled,
    String clientLineColor,
    boolean outgoingDeliveryIndicatorsEnabled,
    boolean serverTreeNotificationBadgesEnabled,

    // --- Hostmask discovery / USERHOST anti-flood ---

    boolean userhostDiscoveryEnabled,
    int userhostMinIntervalSeconds,
    int userhostMaxCommandsPerMinute,
    int userhostNickCooldownMinutes,
    int userhostMaxNicksPerCommand,

    // --- General user info enrichment (fallback) ---

    boolean userInfoEnrichmentEnabled,
    int userInfoEnrichmentUserhostMinIntervalSeconds,
    int userInfoEnrichmentUserhostMaxCommandsPerMinute,
    int userInfoEnrichmentUserhostNickCooldownMinutes,
    int userInfoEnrichmentUserhostMaxNicksPerCommand,
    boolean userInfoEnrichmentWhoisFallbackEnabled,
    int userInfoEnrichmentWhoisMinIntervalSeconds,
    int userInfoEnrichmentWhoisNickCooldownMinutes,
    boolean userInfoEnrichmentPeriodicRefreshEnabled,
    int userInfoEnrichmentPeriodicRefreshIntervalSeconds,
    int userInfoEnrichmentPeriodicRefreshNicksPerTick,
    int monitorIsonFallbackPollIntervalSeconds,
    int notificationRuleCooldownSeconds,
    MemoryUsageDisplayMode memoryUsageDisplayMode,
    int memoryUsageWarningNearMaxPercent,
    boolean memoryUsageWarningTooltipEnabled,
    boolean memoryUsageWarningToastEnabled,
    boolean memoryUsageWarningPushyEnabled,
    boolean memoryUsageWarningSoundEnabled,
    List<NotificationRule> notificationRules) {

  public UiSettings {
    // Preferred default theme (A): Darcula.
    if (theme == null || theme.isBlank()) theme = "darcula";
    if (chatFontFamily == null || chatFontFamily.isBlank()) chatFontFamily = "Monospaced";
    if (chatFontSize <= 0) chatFontSize = 12;

    // Tray settings: if the tray is disabled, ensure tray behaviors are off too.
    if (!trayEnabled) {
      trayCloseToTray = false;
      trayMinimizeToTray = false;
      trayStartMinimized = false;

      trayNotifyHighlights = false;
      trayNotifyPrivateMessages = false;
      trayNotifyConnectionState = false;

      trayNotifyOnlyWhenUnfocused = false;
      trayNotifyOnlyWhenMinimizedOrHidden = false;
      trayNotifySuppressWhenTargetActive = false;

      trayLinuxDbusActionsEnabled = false;
    }
    if (trayNotificationBackendMode == null)
      trayNotificationBackendMode = NotificationBackendMode.AUTO;

    if (imageEmbedsMaxWidthPx < 0) imageEmbedsMaxWidthPx = 0;
    if (imageEmbedsMaxHeightPx < 0) imageEmbedsMaxHeightPx = 0;

    if (timestampFormat == null || timestampFormat.isBlank()) timestampFormat = "HH:mm:ss";
    typingIndicatorsTreeStyle = normalizeTypingTreeIndicatorStyle(typingIndicatorsTreeStyle);

    if (chatHistoryInitialLoadLines < 0) chatHistoryInitialLoadLines = 0;
    if (chatHistoryPageSize <= 0) chatHistoryPageSize = 200;
    if (chatHistoryAutoLoadWheelDebounceMs <= 0) chatHistoryAutoLoadWheelDebounceMs = 2000;
    if (chatHistoryAutoLoadWheelDebounceMs < 100) chatHistoryAutoLoadWheelDebounceMs = 100;
    if (chatHistoryAutoLoadWheelDebounceMs > 30_000) chatHistoryAutoLoadWheelDebounceMs = 30_000;
    if (chatHistoryLoadOlderChunkSize <= 0) chatHistoryLoadOlderChunkSize = 20;
    if (chatHistoryLoadOlderChunkSize < 1) chatHistoryLoadOlderChunkSize = 1;
    if (chatHistoryLoadOlderChunkSize > 500) chatHistoryLoadOlderChunkSize = 500;
    if (chatHistoryLoadOlderChunkDelayMs < 0) chatHistoryLoadOlderChunkDelayMs = 0;
    if (chatHistoryLoadOlderChunkDelayMs > 1_000) chatHistoryLoadOlderChunkDelayMs = 1_000;
    if (chatHistoryLoadOlderChunkEdtBudgetMs <= 0) chatHistoryLoadOlderChunkEdtBudgetMs = 6;
    if (chatHistoryLoadOlderChunkEdtBudgetMs < 1) chatHistoryLoadOlderChunkEdtBudgetMs = 1;
    if (chatHistoryLoadOlderChunkEdtBudgetMs > 33) chatHistoryLoadOlderChunkEdtBudgetMs = 33;
    if (chatHistoryRemoteRequestTimeoutSeconds <= 0) chatHistoryRemoteRequestTimeoutSeconds = 6;
    if (chatHistoryRemoteRequestTimeoutSeconds < 1) chatHistoryRemoteRequestTimeoutSeconds = 1;
    if (chatHistoryRemoteRequestTimeoutSeconds > 120) chatHistoryRemoteRequestTimeoutSeconds = 120;
    if (chatHistoryRemoteZncPlaybackTimeoutSeconds <= 0)
      chatHistoryRemoteZncPlaybackTimeoutSeconds = 18;
    if (chatHistoryRemoteZncPlaybackTimeoutSeconds < 1)
      chatHistoryRemoteZncPlaybackTimeoutSeconds = 1;
    if (chatHistoryRemoteZncPlaybackTimeoutSeconds > 300)
      chatHistoryRemoteZncPlaybackTimeoutSeconds = 300;
    if (chatHistoryRemoteZncPlaybackWindowMinutes <= 0)
      chatHistoryRemoteZncPlaybackWindowMinutes = 360;
    if (chatHistoryRemoteZncPlaybackWindowMinutes < 1)
      chatHistoryRemoteZncPlaybackWindowMinutes = 1;
    if (chatHistoryRemoteZncPlaybackWindowMinutes > 1440)
      chatHistoryRemoteZncPlaybackWindowMinutes = 1440;

    if (commandHistoryMaxSize <= 0) commandHistoryMaxSize = 500;
    if (commandHistoryMaxSize > 500) commandHistoryMaxSize = 500;
    if (chatTranscriptMaxLinesPerTarget < 0) chatTranscriptMaxLinesPerTarget = 0;
    if (chatTranscriptMaxLinesPerTarget > 200_000) chatTranscriptMaxLinesPerTarget = 200_000;

    clientLineColor = normalizeHexOrDefault(clientLineColor, "#6AA2FF");

    // Hostmask discovery / USERHOST anti-flood
    if (userhostMinIntervalSeconds <= 0) userhostMinIntervalSeconds = 7;
    if (userhostMaxCommandsPerMinute <= 0) userhostMaxCommandsPerMinute = 6;
    if (userhostNickCooldownMinutes <= 0) userhostNickCooldownMinutes = 30;
    if (userhostMaxNicksPerCommand <= 0) userhostMaxNicksPerCommand = 5;
    if (userhostMaxNicksPerCommand > 5) userhostMaxNicksPerCommand = 5;

    // General user info enrichment (fallback)
    if (userInfoEnrichmentUserhostMinIntervalSeconds <= 0)
      userInfoEnrichmentUserhostMinIntervalSeconds = 15;
    if (userInfoEnrichmentUserhostMaxCommandsPerMinute <= 0)
      userInfoEnrichmentUserhostMaxCommandsPerMinute = 3;
    if (userInfoEnrichmentUserhostNickCooldownMinutes <= 0)
      userInfoEnrichmentUserhostNickCooldownMinutes = 60;
    if (userInfoEnrichmentUserhostMaxNicksPerCommand <= 0)
      userInfoEnrichmentUserhostMaxNicksPerCommand = 5;
    if (userInfoEnrichmentUserhostMaxNicksPerCommand > 5)
      userInfoEnrichmentUserhostMaxNicksPerCommand = 5;

    if (userInfoEnrichmentWhoisMinIntervalSeconds <= 0)
      userInfoEnrichmentWhoisMinIntervalSeconds = 45;
    if (userInfoEnrichmentWhoisNickCooldownMinutes <= 0)
      userInfoEnrichmentWhoisNickCooldownMinutes = 120;

    if (userInfoEnrichmentPeriodicRefreshIntervalSeconds <= 0)
      userInfoEnrichmentPeriodicRefreshIntervalSeconds = 300;
    if (userInfoEnrichmentPeriodicRefreshNicksPerTick <= 0)
      userInfoEnrichmentPeriodicRefreshNicksPerTick = 2;
    if (userInfoEnrichmentPeriodicRefreshNicksPerTick > 10)
      userInfoEnrichmentPeriodicRefreshNicksPerTick = 10;

    if (monitorIsonFallbackPollIntervalSeconds <= 0) monitorIsonFallbackPollIntervalSeconds = 30;
    if (monitorIsonFallbackPollIntervalSeconds < 5) monitorIsonFallbackPollIntervalSeconds = 5;
    if (monitorIsonFallbackPollIntervalSeconds > 600) monitorIsonFallbackPollIntervalSeconds = 600;

    if (notificationRuleCooldownSeconds < 0) notificationRuleCooldownSeconds = 15;
    if (notificationRuleCooldownSeconds > 3600) notificationRuleCooldownSeconds = 3600;

    if (memoryUsageDisplayMode == null) memoryUsageDisplayMode = MemoryUsageDisplayMode.LONG;
    if (memoryUsageWarningNearMaxPercent <= 0) memoryUsageWarningNearMaxPercent = 5;
    if (memoryUsageWarningNearMaxPercent > 50) memoryUsageWarningNearMaxPercent = 50;

    if (notificationRules == null) notificationRules = List.of();
  }

  /**
   * Back-compat constructor to keep older call sites compiling.
   *
   * <p>Newer user info enrichment fields are defaulted to conservative values and disabled by
   * default.
   */
  public UiSettings(
      String theme,
      String chatFontFamily,
      int chatFontSize,
      boolean autoConnectOnStart,
      boolean imageEmbedsEnabled,
      boolean imageEmbedsCollapsedByDefault,
      int imageEmbedsMaxWidthPx,
      int imageEmbedsMaxHeightPx,
      boolean imageEmbedsAnimateGifs,
      boolean linkPreviewsEnabled,
      boolean linkPreviewsCollapsedByDefault,
      boolean presenceFoldsEnabled,
      boolean ctcpRequestsInActiveTargetEnabled,
      boolean timestampsEnabled,
      String timestampFormat,
      boolean timestampsIncludeChatMessages,
      int chatHistoryInitialLoadLines,
      int chatHistoryPageSize,
      boolean clientLineColorEnabled,
      String clientLineColor,
      boolean userhostDiscoveryEnabled,
      int userhostMinIntervalSeconds,
      int userhostMaxCommandsPerMinute,
      int userhostNickCooldownMinutes,
      int userhostMaxNicksPerCommand) {
    this(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        // Tray defaults (older call sites)
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        true,
        false,
        true,
        true,
        NotificationBackendMode.AUTO,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        true,
        true,
        "dots",
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        true,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        2000,
        20,
        0,
        6,
        false,
        6,
        18,
        360,
        500,
        4000,
        clientLineColorEnabled,
        clientLineColor,
        true,
        true,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,

        // New fields
        false,
        15,
        3,
        60,
        5,
        false,
        45,
        120,
        false,
        300,
        2,
        30,
        15,
        MemoryUsageDisplayMode.LONG,
        5,
        true,
        false,
        false,
        false,
        List.of());
  }

  static String normalizeHexOrDefault(String raw, String fallback) {
    String fb = (fallback == null || fallback.isBlank()) ? "#6AA2FF" : fallback.trim();
    if (raw == null) return fb;
    String s = raw.trim();
    if (s.isEmpty()) return fb;
    if (s.startsWith("#")) s = s.substring(1);
    if (s.startsWith("0x") || s.startsWith("0X")) s = s.substring(2);
    if (s.length() != 6) return fb;
    try {
      int rgb = Integer.parseInt(s, 16);
      int r = (rgb >> 16) & 0xFF;
      int g = (rgb >> 8) & 0xFF;
      int b = rgb & 0xFF;
      return String.format("#%02X%02X%02X", r, g, b);
    } catch (Exception ignored) {
      return fb;
    }
  }

  static String normalizeTypingTreeIndicatorStyle(String raw) {
    String s = raw == null ? "" : raw.trim().toLowerCase(java.util.Locale.ROOT);
    if (s.isEmpty()) return "dots";
    return switch (s) {
      case "dots", "ellipsis" -> "dots";
      case "keyboard", "kbd" -> "keyboard";
      case "glow-dot", "glowdot", "dot", "green-dot", "glowing-green-dot" -> "glow-dot";
      default -> "dots";
    };
  }

  public UiSettings withTheme(String nextTheme) {
    return new UiSettings(
        nextTheme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules);
  }

  public UiSettings withChatFontFamily(String family) {
    return new UiSettings(
        theme,
        family,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules);
  }

  public UiSettings withChatFontSize(int size) {
    return new UiSettings(
        theme,
        chatFontFamily,
        size,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules);
  }

  public UiSettings withImageEmbedsEnabled(boolean enabled) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        enabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules);
  }

  public UiSettings withImageEmbedsCollapsedByDefault(boolean collapsed) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        collapsed,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules);
  }

  public UiSettings withImageEmbedsMaxWidthPx(int maxWidthPx) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        Math.max(0, maxWidthPx),
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules);
  }

  public UiSettings withImageEmbedsMaxHeightPx(int maxHeightPx) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        Math.max(0, maxHeightPx),
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules);
  }

  public UiSettings withLinkPreviewsEnabled(boolean enabled) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        enabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules);
  }

  public UiSettings withLinkPreviewsCollapsedByDefault(boolean collapsed) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        collapsed,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules);
  }

  public UiSettings withPresenceFoldsEnabled(boolean enabled) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        enabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules);
  }

  public UiSettings withTypingIndicatorsEnabled(boolean enabled) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        enabled,
        enabled,
        typingIndicatorsTreeStyle,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules);
  }

  public UiSettings withTypingIndicatorsReceiveEnabled(boolean enabled) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        enabled,
        typingIndicatorsTreeStyle,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules);
  }

  public UiSettings withTimestampsEnabled(boolean enabled) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        enabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules);
  }

  public UiSettings withTimestampFormat(String format) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        timestampsEnabled,
        format,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules);
  }

  public UiSettings withTimestampsIncludeChatMessages(boolean enabled) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        timestampsEnabled,
        timestampFormat,
        enabled,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules);
  }

  public UiSettings withTimestampsIncludePresenceMessages(boolean enabled) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        enabled,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules);
  }

  @Deprecated
  public UiSettings withChatMessageTimestampsEnabled(boolean enabled) {
    return withTimestampsIncludeChatMessages(enabled);
  }

  public UiSettings withMemoryUsageDisplayMode(MemoryUsageDisplayMode mode) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        mode,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules);
  }

  public UiSettings withAutoConnectOnStart(boolean enabled) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        enabled,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules);
  }
}
