@ApplicationModule(
    displayName = "User Interface",
    allowedDependencies = {
      "app",
      "app::api",
      "app::commands",
      "app::commands-spi",
      "app::outbound-filter",
      "app::translation",
      "app::translation-spi",
      "bouncer",
      "config",
      "config::execution",
      "config::properties",
      "config::servers",
      "config::api",
      "dcc::api",
      "diagnostics",
      "ignore",
      "ignore::api",
      "interceptors",
      "irc",
      "irc::backend",
      "irc::ircv3",
      "irc::playback",
      "irc::port",
      "irc::quassel-control",
      "irc::roster",
      "irc::runtime",
      "irc::soju",
      "irc::znc",
      "logging::history",
      "logging::viewer",
      "model",
      "monitor",
      "net",
      "notifications::api",
      "notify::api",
      "notify::api-irc",
      "notify::api-panel",
      "notify::api-pushy",
      "notify::api-sound",
      "notify::api-store",
      "notify::api-text",
      "notify::pushy",
      "notify::sound",
      "notify::spi",
      "plugin::spi",
      "state::api",
      "util"
    })
package cafe.woden.ircclient.ui;

import org.springframework.modulith.ApplicationModule;
