-- Chat history persistence (HSQLDB)

CREATE TABLE chat_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  server_id VARCHAR(128) NOT NULL,
  target VARCHAR(256) NOT NULL,
  ts_epoch_ms BIGINT NOT NULL,
  direction VARCHAR(16) NOT NULL,
  kind VARCHAR(16) NOT NULL,
  from_nick VARCHAR(128),
  text VARCHAR(8192) NOT NULL,
  outgoing_local_echo BOOLEAN NOT NULL,
  soft_ignored BOOLEAN NOT NULL,
  meta CLOB
);

CREATE INDEX idx_chat_log_target_ts ON chat_log(server_id, target, ts_epoch_ms);
CREATE INDEX idx_chat_log_ts ON chat_log(ts_epoch_ms);
