CREATE TABLE chat_redaction_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_id VARCHAR(255) NOT NULL,
    target VARCHAR(512) NOT NULL,
    message_id VARCHAR(512) NOT NULL,
    redacted_at_epoch_ms BIGINT NOT NULL,
    redacted_by VARCHAR(255),
    original_kind VARCHAR(32) NOT NULL,
    original_from_nick VARCHAR(255),
    original_text VARCHAR(8192) NOT NULL,
    original_epoch_ms BIGINT
);

CREATE INDEX ix_chat_redaction_audit_lookup
    ON chat_redaction_audit(server_id, target, message_id, redacted_at_epoch_ms DESC);
