#!/usr/bin/env bash
set -euo pipefail

subject="${1-}"
subject="${subject//$'\r'/}"

if [[ -z "$subject" ]]; then
  echo "ERROR: Missing commit subject." >&2
  exit 1
fi

# Allow merge/revert messages generated by Git.
if [[ "$subject" =~ ^Merge[[:space:]] ]] || [[ "$subject" =~ ^Revert[[:space:]]\" ]]; then
  exit 0
fi

# Allow autosquash workflows.
if [[ "$subject" =~ ^fixup!\  ]]; then
  subject="${subject#fixup! }"
fi
if [[ "$subject" =~ ^squash!\  ]]; then
  subject="${subject#squash! }"
fi

pattern='^(build|chore|ci|docs|feat|fix|perf|refactor|style|test|revert)(\([a-z0-9][a-z0-9._/-]*\))?(!)?: .+'

if [[ ! "$subject" =~ $pattern ]]; then
  cat >&2 <<'EOF'
ERROR: Commit subject must use Conventional Commits.
Format: <type>(<scope>): <subject>
Examples:
  feat(history): add msgid-aware replay dedupe
  fix(ui): preserve viewport anchor while loading older messages
Allowed types:
  build, chore, ci, docs, feat, fix, perf, refactor, style, test, revert
EOF
  echo "Received: $subject" >&2
  exit 1
fi

if ((${#subject} > 72)); then
  echo "WARNING: Commit subject is ${#subject} chars (recommended <= 72)." >&2
fi

